package com.projects.loto_fine;

import android.graphics.Color;

public class Constants {
    public static int NB_LIGNES_CARTON = 3;
    public static int NB_COLONNES_CARTON = 9;

    public static int LOGO_SECONDAIRE_LARGEUR = 157;
    public static int LOGO_SECONDAIRE_HAUTEUR = 36;

    public static int LARGEUR_ECRAN_MAQUETTE = 375;
    public static int HAUTEUR_ECRAN_MAQUETTE = 812;
    public static int LARGEUR_ECRAN_MAQUETTE_HORIZONTALE = 812;
    public static int HAUTEUR_ECRAN_MAQUETTE_HORIZONTALE = 375;

    public static int TOP_LOGO_SECONDAIRE_MAQUETTE = 53;
    public static int BOTTOM_LOGO_SECONDAIRE_MAQUETTE = 89;

    public static int LEFT_LOGO_SECONDAIRE_MAQUETTE_HORIZONTALE = 56;
    public static int TOP_LOGO_SECONDAIRE_MAQUETTE_HORIZONTALE = 21;
    public static int RIGHT_LOGO_SECONDAIRE_MAQUETTE_HORIZONTALE = 213;
    public static int BOTTOM_LOGO_SECONDAIRE_MAQUETTE_HORIZONTALE = 57;

    public static int TOP_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE = 122;
    public static int BOTTOM_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE = 125;

    public static int LEFT_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE_HORIZONTALE = 0;
    public static int TOP_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE_HORIZONTALE = 69;
    public static int RIGHT_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE_HORIZONTALE = 245;
    public static int BOTTOM_PREMIER_SEPARATEUR_HOROZONTAL_MAQUETTE_HORIZONTALE = 72;

    public static int LEFT_TEXTE_LOT = 20;
    public static int TOP_TEXTE_LOT = 141;

    public static int LEFT_TEXTE_LOT_MAQUETTE_HORIZONTALE = 15;
    public static int TOP_TEXTE_LOT_MAQUETTE_HORIZONTALE = 198;

    public static int LEFT_BOUTON_RALENTIR_PARTIE_MAQUETTE = 12;
    public static int TOP_BOUTON_RALENTIR_PARTIE_MAQUETTE = 197;
    public static int RIGHT_BOUTON_RALENTIR_PARTIE_MAQUETTE = 65;
    public static int BOTTOM_BOUTON_RALENTIR_PARTIE_MAQUETTE = 223;

    public static int LEFT_BOUTON_RALENTIR_PARTIE_MAQUETTE_HORIZONTALE = 16;
    public static int TOP_BOUTON_RALENTIR_PARTIE_MAQUETTE_HORIZONTALE = 266;
    public static int RIGHT_BOUTON_RALENTIR_PARTIE_MAQUETTE_HORIZONTALE = 69;
    public static int BOTTOM_BOUTON_RALENTIR_PARTIE_MAQUETTE_HORIZONTALE = 292;

    public static int LEFT_BOUTON_ACCELERER_PARTIE_MAQUETTE = 81;
    public static int TOP_BOUTON_ACCELERER_PARTIE_MAQUETTE = 197;
    public static int RIGHT_BOUTON_ACCELERER_PARTIE_MAQUETTE = 134;
    public static int BOTTOM_BOUTON_ACCELERER_PARTIE_MAQUETTE = 223;

    public static int LEFT_BOUTON_ACCELERER_PARTIE_MAQUETTE_HORIZONTALE = 82;
    public static int TOP_BOUTON_ACCELERER_PARTIE_MAQUETTE_HORIZONTALE = 266;
    public static int RIGHT_BOUTON_ACCELERER_PARTIE_MAQUETTE_HORIZONTALE = 135;
    public static int BOTTOM_BOUTON_ACCELERER_PARTIE_MAQUETTE_HORIZONTALE = 292;

    public static int LEFT_TEXTE_NUMERO_EN_COURS = 270;
    public static int TOP_TEXTE_NUMERO_EN_COURS = 128;
    public static int LEFT_TEXTE_NUMERO = 280;
    public static int TOP_TEXTE_NUMERO = 150;

    public static int LEFT_TEXTE_NUMERO_EN_COURS_MAQUETTE_HORIZONTALE = 176;
    public static int TOP_TEXTE_NUMERO_EN_COURS_MAQUETTE_HORIZONTALE = 198;
    public static int LEFT_TEXTE_NUMERO_MAQUETTE_HORIZONTALE = 163;
    public static int TOP_TEXTE_NUMERO_MAQUETTE_HORIZONTALE = 185;

    public static int LEFT_BOUTON_QUINE_MAQUETTE = 280;
    public static int TOP_BOUTON_QUINE_MAQUETTE = 194;
    public static int RIGHT_BOUTON_QUINE_MAQUETTE = 354;
    public static int BOTTOM_BOUTON_QUINE_MAQUETTE = 231;

    public static int LEFT_BOUTON_QUINE_MAQUETTE_HORIZONTALE = 158;
    public static int TOP_BOUTON_QUINE_MAQUETTE_HORIZONTALE = 268;
    public static int RIGHT_BOUTON_QUINE_MAQUETTE_HORIZONTALE = 232;
    public static int BOTTOM_BOUTON_QUINE_MAQUETTE_HORIZONTALE = 305;

    public static int TOP_DEUXIEME_SEPARATEUR_HOROZONTAL_MAQUETTE = 242;
    public static int BOTTOM_DEUXIEME_SEPARATEUR_HOROZONTAL_MAQUETTE = 245;

    public static int LEFT_SEPARATEUR_VERTICAL_MAQUETTE_HOROZONTALE = 242;
    public static int RIGHT_SEPARATEUR_VERTICAL_MAQUETTE_HOROZONTALE = 245;

    public static int TOP_PREMIER_CARTON_MAQUETTE = 256;
    public static int LEFT_PREMIER_CARTON_MAQUETTE = 38;

    public static int TOP_PREMIER_CARTON_MAQUETTE_HOROZONTALE = 28;
    public static int LEFT_PREMIER_CARTON_MAQUETTE_HOROZONTALE = 376;

    public static int LEFT_BOUTON_CARTONS_PRECEDENTS_MAQUETTE = 27;
    public static int TOP_BOUTON_CARTONS_PRECEDENTS_MAQUETTE = 773;
    public static int RIGHT_BOUTON_CARTONS_PRECEDENTS_MAQUETTE = 145;
    public static int BOTTOM_BOUTON_CARTONS_PRECEDENTS_MAQUETTE = 800;

    public static int LEFT_BOUTON_CARTONS_SUIVANTS_MAQUETTE = 240;
    public static int TOP_BOUTON_CARTONS_SUIVANTS_MAQUETTE = 773;
    public static int RIGHT_BOUTON_CARTONS_SUIVANTS_MAQUETTE = 358;
    public static int BOTTOM_BOUTON_CARTONS_SUIVANTS_MAQUETTE = 800;

    public static int LEFT_BOUTON_QUITTER_MAQUETTE = 153;
    public static int TOP_BOUTON_QUITTER_MAQUETTE = 773;
    public static int RIGHT_BOUTON_QUITTER_MAQUETTE = 227;
    public static int BOTTOM_BOUTON_QUITTER_MAQUETTE = 800;

    public static int LEFT_BOUTON_CARTONS_PRECEDENTS_MAQUETTE_HORIZONTALE = 288;
    public static int TOP_BOUTON_CARTONS_PRECEDENTS_MAQUETTE_HORIZONTALE = 317;
    public static int RIGHT_BOUTON_CARTONS_PRECEDENTS_MAQUETTE_HORIZONTALE = 406;
    public static int BOTTOM_BOUTON_CARTONS_PRECEDENTS_MAQUETTE_HORIZONTALE = 344;

    public static int LEFT_BOUTON_CARTONS_SUIVANTS_MAQUETTE_HORIZONTALE = 633;
    public static int TOP_BOUTON_CARTONS_SUIVANTS_MAQUETTE_HORIZONTALE = 317;
    public static int RIGHT_BOUTON_CARTONS_SUIVANTS_MAQUETTE_HORIZONTALE = 751;
    public static int BOTTOM_BOUTON_CARTONS_SUIVANTS_MAQUETTE_HORIZONTALE = 344;

    public static int LEFT_BOUTON_QUITTER_MAQUETTE_HORIZONTALE = 481;
    public static int TOP_BOUTON_QUITTER_MAQUETTE_HORIZONTALE = 317;
    public static int RIGHT_BOUTON_QUITTER_MAQUETTE_HORIZONTALE = 555;
    public static int BOTTOM_BOUTON_QUITTER_MAQUETTE_HORIZONTALE = 344;

    public static int HAUTEUR_ZONE_CARTON = 480;

    public static int COULEUR_NOIR = Color.BLACK;
    public static int COULEUR_VIOLET = Color.rgb(121, 80, 146);
    public static int COULEUR_BLEU = Color.rgb(70, 195, 234);
    public static int COULEUR_VERT = Color.rgb(57, 168, 45);

    public static int TAILLE_CASE_CARTON = 34;

    //public static String adresseServeurDefaut = "http://localhost";
    public static int portMicroserviceGUIParticipant = 8081;
    public static int portMicroserviceGUIAnimateur = 8083;


    public static int LEFT_BOUTON_TIRER_NUMERO_MAQUETTE = 87;
    public static int TOP_BOUTON_TIRER_NUMERO_MAQUETTE = 103;
    public static int RIGHT_BOUTON_TIRER_NUMERO_MAQUETTE = 188;
    public static int BOTTOM_BOUTON_TIRER_NUMERO_MAQUETTE = 140;

    public static int LEFT_TEXTE_NUMERO_EN_COURS_GESTION_PARTIE_MAQUETTE = 219;
    public static int TOP_TEXTE_NUMERO_EN_COURS_GESTION_PARTIE_MAQUETTE = 103;
    public static int RIGHT_TEXTE_NUMERO_EN_COURS_GESTION_PARTIE_MAQUETTE = 307;

    public static int LEFT_GRILLE_NUMEROS_TIRES_MAQUETTE = 38;
    public static int TOP_GRILLE_NUMEROS_TIRES_MAQUETTE = 212;
    public static int LEFT_PREMIER_NUMERO_GRILLE_MAQUETTE = 44;
    public static int TOP_PREMIER_NUMERO_GRILLE_MAQUETTE = 218;
    public static int TAILLE_CASE_GRILLE_MAQUETTE = 30;

    public static int LEFT_BOUTON_VALIDER_QUINE_MAQUETTE = 80;
    public static int TOP_BOUTON_VALIDER_QUINE_MAQUETTE = 628;
    public static int RIGHT_BOUTON_VALIDER_QUINE_MAQUETTE = 181;
    public static int BOTTOM_BOUTON_VALIDER_QUINE_MAQUETTE = 665;

    public static int LEFT_BOUTON_INVALIDER_QUINE_MAQUETTE = 195;
    public static int TOP_BOUTON_INVALIDER_QUINE_MAQUETTE = 628;
    public static int RIGHT_BOUTON_INVALIDER_QUINE_MAQUETTE = 308;
    public static int BOTTOM_BOUTON_INVALIDER_QUINE_MAQUETTE = 665;

    public static int LEFT_BOUTON_CARTON_SUIVANT_MAQUETTE = 144;
    public static int TOP_BOUTON_CARTON_SUIVANT_MAQUETTE = 679;
    public static int RIGHT_BOUTON_CARTON_SUIVANT_MAQUETTE = 261;
    public static int BOTTOM_BOUTON_CARTON_SUIVANT_MAQUETTE = 716;

    public static int LEFT_BOUTON_QUITTER_GESTION_PARTIE_MAQUETTE = 165;
    public static int TOP_BOUTON_QUITTER_GESTION_PARTIE_MAQUETTE = 739;
    public static int RIGHT_BOUTON_QUITTER_GESTION_PARTIE_MAQUETTE = 239;
    public static int BOTTOM_BOUTON_QUITTER_GESTION_PARTIE_MAQUETTE = 766;

    public static int LEFT_CARTON_GESTION_PARTIE_MAQUETTE = 33;
    public static int TOP_CARTON_GESTION_PARTIE_MAQUETTE = 500;
    public static int RIGHT_CARTON_GESTION_PARTIE_MAQUETTE = 342;
    public static int BOTTOM_CARTON_GESTION_PARTIE_MAQUETTE = 610;

    public static int LEFT_TEXTE_LOT_GESTION_PARTIE_MAQUETTE = 87;
    public static int TOP_TEXTE_LOT_GESTION_PARTIE_MAQUETTE = 165;
    public static int RIGHT_TEXTE_LOT_GESTION_PARTIE_MAQUETTE = 190;
    public static int BOTTOM_TEXTE_LOT_GESTION_PARTIE_MAQUETTE = 200;

    public static int NB_SECONDES_AVANT_MAJ_INFOS_TABLETTE_DEFAUT = 5;

    public static int TAILLE_MAX_CP = 10;
    public static int TAILLE_MAX_VILLE = 50;
    public static int TAILLE_MAX_ADRESSE = 100;
}
